### ISSUE TITLE
[Question] Does intermediary map generating require MojMaps?

### ISSUE THREAD

**Issue by teddyxlandlee** [FabricMC/intermediary#27]
As a Fabric modder, I am curious about how the intermediary mapping is produced.  
1. Is it auto-generated or artificially uploaded?  
2. What's the basis of the generation?  
+ MojMaps?
+ Or something like AI that can compare classes in JARs between versions?  

Thank you.

**Comment by Juuxel** [comment]
1. Artificially uploaded since the generation usually needs manual matching.
2. Most names are automatically matched between the previous and current versions using [Matcher](https://github.com/FabricMC/Matcher)'s automatic code detection, but it can't detect every change so:
- Mojang names are also used for matching now that they are available. In older versions like 1.14 snapshots, they obviously weren't used.
- The rest is manually matched

See also what the wiki says about the process: https://fabricmc.net/wiki/tutorial:updating_yarn#matching

**Comment by Player3324** [comment]
At large it is a sort of AI approach, not the deep learning variety in particular though. Mojang's mappings can be used to make the process faster and potentially a little more robust, but that's not a huge impact. The tooling is set up to successfully work with just the obfuscated jars, there were plenty of releases where we had no access to the Proguard mappings at all. It is surprising how much data can be recovered from the obfuscated output alone.

Manual matching is used to complement the process for cases where the algorithm is too unsure or lacks the bigger picture, but it is generally based on automatically determined similarity scores. It allows for higher deemed-equivalent thresholds and thus more accurate results.
